spring.application.name=springSecurity1

spring.security.user.name=${SECURITY_USERNAME:user}
spring.security.user.password=${SECURITY_PASSWORD:123}

logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}